name: Publish Docker Image
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: docker/metadata-action@latest
        id: metadata
        with:
          images: ghcr.io/whallin/caddy-cloudflare
      - uses: docker/setup-buildx-action@latest
      - uses: docker/login-action@latest
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@latest
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
